spring:
  cloud:
    gateway:
      routes:
        - id: posts-route
          uri: http://localhost:8081
          predicates:
            - Path=/posts/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, Joe's Java Studio
        - id: comments-route
          uri: http://localhost:8082
          predicates:
            - Path=/comments/**
          filters:
            - PrefixPath=/api
            - name: AddResponseHeader
              args:
                name: X-Powered-By
                value: IntelliJ
